#!/usr/bin/env python3
import argparse

from initramfs_wrap import create_initramfs


def main():
    parser = argparse.ArgumentParser(description="Create a minimalistic initramfs")
    parser.add_argument(
        "--initramfs",
        help="Destination file",
        required=True,
    )
    parser.add_argument(
        "--chroot",
        help="Chroot from debootstrap-stage1",
        required=True,
    )
    args = parser.parse_args()
    create_initramfs(args.initramfs, args.chroot)


if __name__ == "__main__":
    main()
