#!/usr/bin/env python3
import argparse

from initramfs_wrap import add_cache_dir_parser, fetch_vmlinux


def main():
    parser = argparse.ArgumentParser(description="Download linux kernel")
    add_cache_dir_parser(parser)
    parser.add_argument("arch", help="Architecture")
    args = parser.parse_args()
    print(fetch_vmlinux(args.arch, args.cache_dir))


if __name__ == "__main__":
    main()
